variables:
  - group: RegistrySecrets

trigger:
  branches: # Branch names to include or exclude for triggering a run.
    include: [ 'main' ]
  paths: # File paths to include or exclude for triggering a run.
    include: [ 'execution-environments/ztp-ee/' ]

extends:
  template: ../../.azure/pipelines-ee-base.yml
  parameters:
    REGISTRY_USERNAME: $(REGISTRY_USERNAME)
    REGISTRY_PASSWORD: $(REGISTRY_PASSWORD)
    REGISTRY_PATH: kenmoini
    EE_IMAGE_NAME: ansible-ztp-ee
    EE_FOLDER_NAME: execution-environments/ztp-ee
