---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: kubernetes.core
  - name: community.okd
  - name: community.crypto
  - name: community.vmware
    #version: 1.17.0
    version: 4.0.1
  - name: community.general
  - name: infra.controller_configuration
  - name: kenmoini.powerdns_admin
  - name: kenmoini.redfish
  - name: kenmoini.phpipam
  
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
    version: ">=4.6.0"
  - name: ansible.eda
  - name: infra.aap_configuration
