# File: pipeline-ee-base.yml
parameters:
  - name: REGISTRY_HOSTNAME # The hostname of the registry to push to
    type: string
    default: "quay.io"
  - name: REGISTRY_PATH     # Path to push to in the registry, eg your username
    type: string
    default: ""

  - name: REGISTRY_USERNAME # Needed for target push registry login
    type: string
    default: ""
  - name: REGISTRY_PASSWORD # Needed for target push registry login
    type: string
    default: ""

  - name: EE_IMAGE_NAME     # Image Name for the EE
    type: string
    default: ""
  - name: EE_IMAGE_TAG      # Image tag, must be one tag for image build, defaults to latest
    type: string
    default: "latest"
  - name: EE_FOLDER_NAME    # Name of the folder in the repo where the EE is located
    type: string
    default: ""

stages:
  - stage: build_ee

    variables:
      - name: currentDate
        value: $[ format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime) ]

    pool:
      vmImage: ubuntu-latest

    jobs:
      - displayName: Assert that all needed inputs are provided
        bash: |
          if [ -z "$REGISTRY_USERNAME" ]; then
            echo "REGISTRY_USERNAME was not provided!"
            exit 1
          fi
          if [ -z "$REGISTRY_PASSWORD" ]; then
            echo "REGISTRY_PASSWORD was not provided!"
            exit 1
          fi
          if [ -z "$EE_IMAGE_NAME" ]; then
            echo "EE_IMAGE_NAME was not provided!"
            exit 1
          fi
        env:
          REGISTRY_USERNAME: ${{ parameters['REGISTRY_USERNAME'] }}
          REGISTRY_PASSWORD: ${{ parameters['REGISTRY_PASSWORD'] }}
          EE_IMAGE_NAME: ${{ parameters['EE_IMAGE_NAME'] }}

      - displayName: Install ansible-builder via pip
        script: pip install ansible-builder==3.0.0

      - displayName: Install/Update Podman
        script: sudo apt-get install podman -y

      - displayName: Display Build Parameters
        bash: |
          env
          echo $(currentDate)
          echo $REGISTRY_USERNAME
